# Introduction 


The zone of transition between aquatic and terrestrial habitats, i.e., the riparian zone, is characterised by unique soil, hydrologic, and biotic conditions and strong interactions with the associated waterbody. Degradation of the riparian zone has implications for stream functioning including sedimentation, nutrient concentration, terrestrial food subsidies, and water temperature ([@allan2003] Bowler et al. 2012). Riparian vegetation influences stream temperatures by intercepting solar radiation, shading the stream and catchments where water flows into streams and infiltrates into the groundwater (DFO 2020a). Because of this, the riparian zone has been identified as critical habitat for several aquatic species-at-risk, often implemented as fixed-widths from the high water mark of the waterbody. 

Fixed-width critical habitat determinations may, like fixed-width riparian buffers, be administratively simple to implement, however, they require evaluation of their effectiveness (Richardson et al. 2012). For example, monitoring the influence of the riparian vegetation on water temperature is an integral step for refining the current delineation of critical habitat within the riparian zone.  

In the Rocky Mountains’ Eastern Slopes Priority Area, Athabasca Rainbow Trout is listed as Endangered and Bull Trout is listed as Special Concern. In addition, Bull Trout is listed as Threatened in the neighbouring Saskatchewan-Nelson River DU. Both Athabasca Rainbow Trout and Bull Trout require cold water for survival and are therefore susceptible to watershed disturbances that contribute to increased summer water temperatures (DFO 2020b, DFO 2017). Salmonids are particularly susceptible to increasing summer maximum stream temperatures, which have been identified as barriers to recovery (Wondzell et al. 2018). 
Further research is required to refine the understanding of the features, attributes, and boundaries of the currently identified riparian critical habitat (DFO 2020b, DFO 2017). Using a precautionary approach, a width of 30 m from the high water mark on both stream banks is included as Athabasca Rainbow Trout (DFO 2020b) and Bull Trout (DFO 2017) critical habitat. This delineation follows the critical habitat identified for Westslope Cutthroat Trout and is based on the approach taken by Alberta Agriculture and Forestry to define riparian buffer widths (DFO 2019). To be able to scientifically defend the 30 m fixed-width riparian critical habitat for Athabasca Rainbow Trout and Bull Trout, the effects of the riparian vegetation on water temperature needs to be studied and effectiveness of the buffer width validated.  In addition, to determine the width of riparian zone necessary to be protected as critical habitat, quantitative data specific to Bull Trout in Alberta and/or the development of guidance materials to refine riparian critical habitat standards were identified as key knowledge gaps (DFO 2020c).
Here, we propose an expansion into the riparian zone of the instream water temperature monitoring that is already occurring in the priority area to provide evidence to support the delineation of riparian critical habitat in terms of its influence on water temperature. Several streams in the watershed chosen for this project were sampled last year for water temperature, dissolved oxygen, and water level, along with invertebrate and fish sampling. 

Hence, the proposed research project has the following objectives:
1.	Install a network of data loggers instream and at increasing distances from the stream into the riparian zone to monitor changes in light and temperature.
2.	Map stream temperature and riparian canopy cover using an unmanned aerial vehicle (UAV) equipped with an infrared camera and satellite imagery to compare estimates. 
3.	Obtain direct measurements of canopy cover in the logger transects instream and in the riparian zone to determine the relationship between light levels and canopy cover.
4.	Analyse logger data after one season (spring – fall) to determine how far away from the stream the canopy cover in the riparian zone influences stream temperature. 
5.	Extrapolate the results of the analyses using the estimated canopy cover from the UAV and satellite imagery to predict a geospatial area for riparian critical habitat. 
6.	Create a model to support a refined classification of riparian critical habitat, based on canopy cover estimates from UAV and/or satellite imagery.

 
