# Methods

## Location
The monitoring will occur within the Rocky Mountains’ Eastern Slopes Priority Area (Alberta). Specifically the Upper McLeod River watershed (HUC 6: 170201) where both Athabasca Rainbow Trout and Bull Trout reside. The specific streams that will be used are Anderson Creek (lat/long: 53.321077, -117.375688), Wampus Creek (lat/long: 53.158748, -117.25863), and Mackenzie Creek (lat/long:  53.058459, -117.182687).  Three additional streams are TBD but will be placed in streams with proposed logging for 2023. 


## Sampling Methods
In the spring and early summer of 2022, temperature and light data loggers will be installed in six streams every 1 m from the centre of the stream, and every 5 m in transects extending 35 m into the riparian zone on one side of the stream (~10 loggers per transect). There will be five transects per stream (on randomly chosen, alternating sides of the stream perpendicular to the stream axis) spaced 60 m apart, along with an additional instream logger 60 m downstream of the last transect to capture downstream effects. A water level logger will be installed at the most upstream logger location to record changes in water depth during the sampling period. At the same time, the crews will obtain direct measurements of water depth and canopy cover at the data logger transects every 2.5 m, instream and in the riparian zone to provide canopy cover estimates for the spring. 

In addition, crews will use the UAV to map the stream widths, riparian forest widths, and canopy cover for a total of 1km of stream length. The UAV data will be processed along with satellite imagery from the same location using software to remove outliers and classify the remaining points into stream, ground, and non-ground points using a filtering algorithm. 
At the same time as the UAV flights, the crews will obtain direct measurements of canopy cover at the data logger transects every 2.5 m, instream and in the riparian zone to provide canopy cover estimates in the summer at peak canopy cover. Canopy cover estimates will also be obtained in the fall of 2022 when the loggers are retrieved. 

In late-summer, early fall of 2022, point estimates of canopy cover, light, and temperature data will be evaluated using empirical dynamic modelling to determine how far away from the stream does the canopy cover in the riparian zone influence stream temperature. The interactions between the riparian zone and the aquatic habitat are complex and dynamic, with multiple factors at play. Empirical dynamic modelling is a dynamical systems approach that does not assume constancy or separability of ecosystems into independent components with fixed relationships, and can be used to determine cause and effect relationships for the ecosystem drivers considered (e.g., canopy cover, temperature, light) and drivers not considered (Munch et al. 2020). The analyses will be applied to each stream separately, with all streams combined, and then compared to determine if the resulting relationship is an artefact of riparian-temperature dynamics in a random stream or representative of a broader class of streams.

In late fall 2022 and early winter 2023, using the estimates of riparian width and canopy cover from the UAV footage and satellite imagery, results of the above analyses will be extrapolated across the 700 m stretch of each stream to provide a refined map of riparian critical habitat in terms of stream temperature. Depending on the outcome of the analysis, a model will be created using satellite imagery to provide support for the refinement of the classification of riparian critical habitat calibrated to the water temperature requirements of Athabasca Rainbow Trout and Bull Trout. This model will also apply to other cold water species, for example Westslope Cutthroat Trout, in similar habitats.
